# Generated by Django 2.0.6 on 2018-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_link', models.URLField()),
                ('title', models.CharField(max_length=64)),
                ('img', models.FileField(upload_to='')),
                ('lid', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'news',
            },
        ),
    ]
