# Generated by Django 2.0.6 on 2018-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnews',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
