# Generated by Django 2.0.6 on 2018-06-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0003_remove_shortnews_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortnews',
            old_name='date',
            new_name='datetime',
        ),
    ]
