# Generated by Django 2.0.6 on 2018-06-23 15:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_auto_20180613_1631'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('with_author', django.db.models.manager.Manager()),
            ],
        ),
    ]
