# Generated by Django 2.0.6 on 2018-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=64)),
                ('checked', models.BooleanField()),
            ],
            options={
                'verbose_name': 'one name',
                'verbose_name_plural': 'plural name',
            },
        ),
    ]
