# Generated by Django 2.0.6 on 2018-06-20 15:38

from django.db import migrations


def migrate_task(apps, schema_editor):
    Task = apps.get_model('my_app', 'Task')
    Task.objects.create(text='migrate1', checked=1)
    Task.objects.create(text='migrate2', checked=0)


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20180609_0826'),
    ]

    operations = [
        migrations.RunPython(migrate_task, migrations.RunPython.noop)
    ]
