# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortly_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortly',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_target', models.URLField(max_length=250, unique=True)),
                ('click_count', models.PositiveSmallIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
    ]
