# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortly_app', '0002_shortly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortly',
            options={},
        ),
    ]
