# Generated by Django 2.0.6 on 2018-06-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_auto_20180613_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='bkj', to='book_store.Tag'),
        ),
        migrations.AddField(
            model_name='booktags',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.Book'),
        ),
        migrations.AddField(
            model_name='booktags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booktags', to='book_store.Tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags2',
            field=models.ManyToManyField(related_name='bkjaaaaaaaaa', through='book_store.BookTags', to='book_store.Tag'),
        ),
    ]
